# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: peering.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'peering.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpeering.proto\x12\x07peering\"3\n\x11UploadFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"&\n\x12UploadFileResponse\x12\x10\n\x08response\x18\x01 \x01(\t2W\n\x0ePeeringService\x12\x45\n\nUploadFile\x12\x1a.peering.UploadFileRequest\x1a\x1b.peering.UploadFileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'peering_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADFILEREQUEST']._serialized_start=26
  _globals['_UPLOADFILEREQUEST']._serialized_end=77
  _globals['_UPLOADFILERESPONSE']._serialized_start=79
  _globals['_UPLOADFILERESPONSE']._serialized_end=117
  _globals['_PEERINGSERVICE']._serialized_start=119
  _globals['_PEERINGSERVICE']._serialized_end=206
# @@protoc_insertion_point(module_scope)
